### ISSUE TITLE
AttributeError: 'AircraftRequests' object has no attribute 'EnvironmentData'

### ISSUE THREAD

**Issue by douxyeti** [hankhank10/Python-SimConnect#12]
I cant go past this error when running the script.

Traceback (most recent call last):
  File "C:\Users\mario\Desktop\Nouveau dossier\MSFS2020-cockpit-companion-master\MSFS2020-cockpit-companion-master\glass_server.py", line 14, in <module>
    aq = AircraftRequests(sm, _time=10)
  File "C:\Users\mario\AppData\Local\Programs\Python\Python39\lib\site-packages\SimConnect\RequestList.py", line 214, in __init__
    self.list.append(self.EnvironmentData)
AttributeError: 'AircraftRequests' object has no attribute 'EnvironmentData'

What do I miss?
Thanks for the help

**Comment by bigsby-exe** [comment]
I had a similar issue with the exact same error message. For me the fix has been to install SimConnect version 0.4.24 rather than the latest version of 0.4.25

Link to my issue on the topic: [Python-SimConnect/issues/115](https://github.com/odwdinc/Python-SimConnect/issues/115)

**Comment by Day0Dreamer** [comment]
+1 having the same issue
